apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Data Center 4
namespace: distributed-semaphore-dc4
namePrefix: dc4-

resources:
  - ../../base

labels:
  - pairs:
      topology.kubernetes.io/region: dc4
    includeSelectors: false

patches:
  - path: deployment-patch.yaml
