apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Data Center 1
namespace: distributed-semaphore-dc1
namePrefix: dc1-

resources:
  - ../../base

labels:
  - pairs:
      topology.kubernetes.io/region: dc1
    includeSelectors: false

patches:
  - path: deployment-patch.yaml
