apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Data Center 3
namespace: distributed-semaphore-dc3
namePrefix: dc3-

resources:
  - ../../base

labels:
  - pairs:
      topology.kubernetes.io/region: dc3
    includeSelectors: false

patches:
  - path: deployment-patch.yaml
